// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\HDLFullySerialLMSModel\Adder.v
// Created: 2024-02-10 22:35:17
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Adder
// Source Path: HDLFullySerialLMSModel/HDL LMS Algorithm/Filter/Accumulator/Adder
// Hierarchy Level: 3
// Model version: 6.2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Adder
          (clk,
           reset,
           enb,
           enb_1,
           rst,
           a,
           out1);


  input   clk;
  input   reset;
  input   enb;
  input   enb_1;
  input   rst;
  input   signed [38:0] a;  // sfix39_En33
  output  signed [26:0] out1;  // sfix27_En20


  reg signed [26:0] out1_1;  // sfix27_En20
  reg signed [26:0] reg_rsvd;  // sfix27
  reg signed [26:0] breg;  // sfix27
  reg  state;
  reg signed [26:0] reg_next;  // sfix27_En20
  reg signed [26:0] breg_next;  // sfix27_En20
  reg  state_next;
  reg signed [40:0] u;  // sfix41_En33
  reg signed [40:0] add_cast;  // sfix41_En33
  reg signed [40:0] add_cast_0;  // sfix41_En33


  always @(posedge clk or posedge reset)
    begin : Adder_1_process
      if (reset == 1'b1) begin
        state <= 1'b1;
        reg_rsvd <= 27'sb000000000000000000000000000;
        breg <= 27'sb000000000000000000000000000;
      end
      else begin
        if (enb) begin
          reg_rsvd <= reg_next;
          breg <= breg_next;
          state <= state_next;
        end
      end
    end

  always @(a, breg, enb_1, reg_rsvd, rst, state) begin
    reg_next = reg_rsvd;
    state_next = state;
    // This logic fuctions as accumulator of the filter. It casts the data based
    // on the double, single or fixed-point real- or complex-valued input
    // signals.
    add_cast = {{2{a[38]}}, a};
    add_cast_0 = {breg[26], {breg, 13'b0000000000000}};
    u = add_cast + add_cast_0;
    if (rst) begin
      reg_next = 27'sb000000000000000000000000000;
    end
    else if (enb_1) begin
      reg_next = u[39:13];
    end
    if (rst || state) begin
      breg_next = 27'sb000000000000000000000000000;
    end
    else begin
      breg_next = u[39:13];
    end
    if (rst) begin
      state_next = 1'b0;
    end
    else if (enb_1) begin
      state_next = 1'b1;
    end
    out1_1 = reg_rsvd;
  end



  assign out1 = out1_1;

endmodule  // Adder
