// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\HDLFullySerialLMSModel\Controller.v
// Created: 2024-02-10 22:35:17
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Controller
// Source Path: HDLFullySerialLMSModel/HDL LMS Algorithm/Filter/Coefficient Memory/Coeff Controller/Controller
// Hierarchy Level: 4
// Model version: 6.2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Controller
          (clk,
           reset,
           enb,
           in,
           enb_1,
           rst,
           out_re,
           out_im,
           wrAdrs,
           enbWr);


  input   clk;
  input   reset;
  input   enb;
  input   signed [22:0] in;  // sfix23_En20
  input   enb_1;
  input   rst;
  output  signed [22:0] out_re;  // sfix23_En20
  output  signed [22:0] out_im;  // sfix23_En20
  output  [4:0] wrAdrs;  // ufix5
  output  enbWr;


  reg signed [22:0] out_re_1;  // sfix23_En20
  reg signed [22:0] out_im_1;  // sfix23_En20
  reg [4:0] wrAdrs_1;  // ufix5
  reg  enbWr_1;
  reg  state;
  reg [4:0] count;  // ufix5
  reg  state_next;
  reg [4:0] count_next;  // ufix5
  reg  cntHigh;


  always @(posedge clk or posedge reset)
    begin : Controller_1_process
      if (reset == 1'b1) begin
        state <= 1'b0;
        count <= 5'b00000;
      end
      else begin
        if (enb) begin
          state <= state_next;
          count <= count_next;
        end
      end
    end

  always @(count, enb_1, in, rst, state) begin
    state_next = state;
    count_next = count;
    // It provides input control signals to write updated filter coefficients to
    // the RAM.
    enbWr_1 = state && ( ! rst);
    cntHigh = (count == 5'b01111) && state;
    if (rst) begin
      state_next = 1'b0;
    end
    else if (enb_1) begin
      state_next = 1'b1;
    end
    else if (cntHigh) begin
      state_next = 1'b0;
    end
    // counter logic
    if ((cntHigh || enb_1) || rst) begin
      count_next = 5'b00000;
    end
    else if (state) begin
      count_next = count + 5'b00001;
    end
    out_re_1 = in;
    out_im_1 = 23'sb00000000000000000000000;
    wrAdrs_1 = count;
  end



  assign out_re = out_re_1;

  assign out_im = out_im_1;

  assign wrAdrs = wrAdrs_1;

  assign enbWr = enbWr_1;

endmodule  // Controller