// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\HDLFullySerialLMSModel\Data_Control.v
// Created: 2024-02-10 22:35:17
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Data_Control
// Source Path: HDLFullySerialLMSModel/HDL LMS Algorithm/Data Control
// Hierarchy Level: 1
// Model version: 6.2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Data_Control
          (clk,
           reset,
           enb,
           reset_1,
           validIn,
           adapt,
           adaptOut,
           validOut,
           readyOut);


  input   clk;
  input   reset;
  input   enb;
  input   reset_1;
  input   validIn;
  input   adapt;
  output  adaptOut;
  output  validOut;
  output  readyOut;




  Input_Control u_Input_Control (.clk(clk),
                                 .reset(reset),
                                 .enb(enb),
                                 .reset_1(reset_1),
                                 .validIn(validIn),
                                 .adapt(adapt),
                                 .adaptOut(adaptOut),
                                 .validOut(validOut),
                                 .readyOut(readyOut)
                                 );

endmodule  // Data_Control