// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\HDLFullySerialLMSModel\Data_Conversion.v
// Created: 2024-02-10 22:35:17
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Data_Conversion
// Source Path: HDLFullySerialLMSModel/HDL LMS Algorithm/Coefficient Update/Multiplier1/Data Conversion
// Hierarchy Level: 3
// Model version: 6.2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Data_Conversion
          (u,
           u1,
           y);


  input   signed [40:0] u;  // sfix41_En34
  input   signed [22:0] u1;  // sfix23_En16
  output  signed [22:0] y;  // sfix23_En21




  //#Codegen
  // The wordlength and fractional length adjusted based on simulation
  assign y = u[35:13];



endmodule  // Data_Conversion