// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\HDLFullySerialLMSModel\Data_Conversion_block.v
// Created: 2024-02-10 22:35:17
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Data_Conversion_block
// Source Path: HDLFullySerialLMSModel/HDL LMS Algorithm/Coefficient Update/Multiplier2/Data Conversion
// Hierarchy Level: 3
// Model version: 6.2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Data_Conversion_block
          (u,
           const_rsvd);


  input   signed [15:0] u;  // sfix16_En13
  output  signed [16:0] const_rsvd;  // sfix17_En13




  //#Codegen
  // The wordlength and fractional length adjusted based on simulation
  assign const_rsvd = {u[15], u};



endmodule  // Data_Conversion_block