// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\HDLFullySerialLMSModel\DataType_Conversion.v
// Created: 2024-02-10 22:35:17
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: DataType_Conversion
// Source Path: HDLFullySerialLMSModel/HDL LMS Algorithm/Coefficient Update/Filter Error/DataType Conversion
// Hierarchy Level: 3
// Model version: 6.2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module DataType_Conversion
          (clk,
           reset,
           enb,
           enb_1,
           u,
           u1,
           out1,
           out2);


  input   clk;
  input   reset;
  input   enb;
  input   enb_1;
  input   signed [15:0] u;  // sfix16_En13
  input   signed [26:0] u1;  // sfix27_En20
  output  signed [22:0] out1;  // sfix23_En16
  output  signed [22:0] out2;  // sfix23_En16


  reg signed [22:0] out1_1;  // sfix23_En16
  reg signed [22:0] out2_1;  // sfix23_En16
  reg signed [22:0] reg_rsvd;  // sfix23
  reg signed [22:0] reg_next;  // sfix23_En16


  always @(posedge clk or posedge reset)
    begin : DataType_Conversion_1_process
      if (reset == 1'b1) begin
        reg_rsvd <= 23'sb00000000000000000000000;
      end
      else begin
        if (enb) begin
          reg_rsvd <= reg_next;
        end
      end
    end

  always @(enb_1, reg_rsvd, u, u1) begin
    reg_next = reg_rsvd;
    //#Codegen
    // The wordlength and fractional length adjusted based on simulation
    if (enb_1) begin
      reg_next = {{4{u[15]}}, {u, 3'b000}};
    end
    out1_1 = reg_rsvd;
    out2_1 = u1[26:4];
  end



  assign out1 = out1_1;

  assign out2 = out2_1;

endmodule  // DataType_Conversion