// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\HDLFullySerialLMSModel\multiplier.v
// Created: 2024-02-10 22:35:17
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: multiplier
// Source Path: HDLFullySerialLMSModel/HDL LMS Algorithm/Coefficient Update/Multiplier2/multiplier
// Hierarchy Level: 3
// Model version: 6.2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module multiplier
          (clk,
           enb,
           in1,
           in2,
           out);


  input   clk;
  input   enb;
  input   signed [16:0] in1;  // sfix17_En13
  input   signed [22:0] in2;  // sfix23_En21
  output  signed [39:0] out;  // sfix40_En34


  reg signed [39:0] out_1;  // sfix40_En34
  reg signed [16:0] in1d1;  // sfix17
  reg signed [16:0] in1d2;  // sfix17
  reg signed [22:0] in2d1;  // sfix23
  reg signed [22:0] in2d2;  // sfix23
  reg signed [39:0] yreg1;  // sfix40
  reg signed [39:0] yreg2;  // sfix40

  initial begin
    in1d1 = 17'sb00000000000000000;
    in1d2 = 17'sb00000000000000000;
    in2d1 = 23'sb00000000000000000000000;
    in2d2 = 23'sb00000000000000000000000;
    out_1 = 40'sh0000000000;
    yreg1 = 40'sh0000000000;
    yreg2 = 40'sh0000000000;
  end

  always @(posedge clk)
    begin : multiplier_1_process
      if (enb) begin
        in1d2 <= in1d1;
        in1d1 <= in1;
        in2d2 <= in2d1;
        in2d1 <= in2;
        out_1 <= yreg1;
        yreg1 <= yreg2;
        yreg2 <= in1d2 * in2d2;
      end
    end



  assign out = out_1;

endmodule  // multiplier