
// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\HDLFullySerialLMSModel\multiplier_block.v
// Created: 2024-02-10 22:35:17
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: multiplier_block
// Source Path: HDLFullySerialLMSModel/HDL LMS Algorithm/Filter/Multiplier/multiplier
// Hierarchy Level: 3
// Model version: 6.2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module multiplier_block
          (clk,
           enb,
           in1,
           in2,
           out);


  input   clk;
  input   enb;
  input   signed [15:0] in1;  // sfix16_En13
  input   signed [22:0] in2;  // sfix23_En20
  output  signed [38:0] out;  // sfix39_En33


  reg signed [38:0] out_1;  // sfix39_En33
  reg signed [15:0] in1d1;  // sfix16
  reg signed [15:0] in1d2;  // sfix16
  reg signed [22:0] in2d1;  // sfix23
  reg signed [22:0] in2d2;  // sfix23
  reg signed [38:0] yreg1;  // sfix39
  reg signed [38:0] yreg2;  // sfix39

  initial begin
    in1d1 = 16'sb0000000000000000;
    in1d2 = 16'sb0000000000000000;
    in2d1 = 23'sb00000000000000000000000;
    in2d2 = 23'sb00000000000000000000000;
    out_1 = 39'sh0000000000;
    yreg1 = 39'sh0000000000;
    yreg2 = 39'sh0000000000;
  end

  always @(posedge clk)
    begin : multiplier_process
      if (enb) begin
        in1d2 <= in1d1;
        in1d1 <= in1;
        in2d2 <= in2d1;
        in2d1 <= in2;
        out_1 <= yreg1;
        yreg1 <= yreg2;
        yreg2 <= in1d2 * in2d2;
      end
    end



  assign out = out_1;

endmodule  // multiplier_block