// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\HDLFullySerialLMSModel\Multiplier1.v
// Created: 2024-02-10 22:35:17
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Multiplier1
// Source Path: HDLFullySerialLMSModel/HDL LMS Algorithm/Coefficient Update/Multiplier1
// Hierarchy Level: 2
// Model version: 6.2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Multiplier1
          (clk,
           enb,
           stepSize,
           filterError,
           mulout);


  input   clk;
  input   enb;
  input   [17:0] stepSize;  // ufix18_En18
  input   signed [22:0] filterError;  // sfix23_En16
  output  signed [22:0] mulout;  // sfix23_En21


  reg [17:0] Delay1_reg [0:1];  // ufix18 [2]
  wire [17:0] Delay1_reg_next [0:1];  // ufix18_En18 [2]
  wire [17:0] Delay1_out1;  // ufix18_En18
  reg signed [22:0] Delay2_reg [0:1];  // sfix23 [2]
  wire signed [22:0] Delay2_reg_next [0:1];  // sfix23_En16 [2]
  wire signed [22:0] Delay2_out1;  // sfix23_En16
  wire signed [18:0] Product_cast;  // sfix19_En18
  wire signed [41:0] Product_mul_temp;  // sfix42_En34
  wire signed [40:0] Product_out1;  // sfix41_En34
  reg signed [40:0] Delay_out1;  // sfix41_En34
  wire signed [22:0] y;  // sfix23_En21
  reg signed [31:0] Delay1_t_0_0;  // int32
  reg signed [31:0] Delay1_t_1;  // int32
  reg signed [31:0] Delay2_t_0_0;  // int32
  reg signed [31:0] Delay2_t_1;  // int32

  initial begin

    for(Delay1_t_1 = 32'sd0; Delay1_t_1 <= 32'sd1; Delay1_t_1 = Delay1_t_1 + 32'sd1) begin
      Delay1_reg[Delay1_t_1] = 18'b000000000000000000;
    end


    for(Delay2_t_1 = 32'sd0; Delay2_t_1 <= 32'sd1; Delay2_t_1 = Delay2_t_1 + 32'sd1) begin
      Delay2_reg[Delay2_t_1] = 23'sb00000000000000000000000;
    end

    Delay_out1 = 41'sh00000000000;
  end

  always @(posedge clk)
    begin : Delay1_process
      if (enb) begin
        for(Delay1_t_0_0 = 32'sd0; Delay1_t_0_0 <= 32'sd1; Delay1_t_0_0 = Delay1_t_0_0 + 32'sd1) begin
          Delay1_reg[Delay1_t_0_0] <= Delay1_reg_next[Delay1_t_0_0];
        end
      end
    end

  assign Delay1_out1 = Delay1_reg[1];
  assign Delay1_reg_next[0] = stepSize;
  assign Delay1_reg_next[1] = Delay1_reg[0];



  always @(posedge clk)
    begin : Delay2_process
      if (enb) begin
        for(Delay2_t_0_0 = 32'sd0; Delay2_t_0_0 <= 32'sd1; Delay2_t_0_0 = Delay2_t_0_0 + 32'sd1) begin
          Delay2_reg[Delay2_t_0_0] <= Delay2_reg_next[Delay2_t_0_0];
        end
      end
    end

  assign Delay2_out1 = Delay2_reg[1];
  assign Delay2_reg_next[0] = filterError;
  assign Delay2_reg_next[1] = Delay2_reg[0];



  assign Product_cast = {1'b0, Delay1_out1};
  assign Product_mul_temp = Product_cast * Delay2_out1;
  assign Product_out1 = Product_mul_temp[40:0];



  always @(posedge clk)
    begin : Delay_process
      if (enb) begin
        Delay_out1 <= Product_out1;
      end
    end



  Data_Conversion u_Data_Conversion (.u(Delay_out1),  // sfix41_En34
                                     .u1(Delay2_out1),  // sfix23_En16
                                     .y(y)  // sfix23_En21
                                     );

  assign mulout = y;

endmodule  // Multiplier1