
// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\HDLFullySerialLMSModel\Multiplier_block1.v
// Created: 2024-02-10 22:35:17
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Multiplier_block1
// Source Path: HDLFullySerialLMSModel/HDL LMS Algorithm/Filter/Multiplier
// Hierarchy Level: 2
// Model version: 6.2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Multiplier_block1
          (clk,
           enb,
           in1,
           in2,
           mulOut);


  input   clk;
  input   enb;
  input   signed [15:0] in1;  // sfix16_En13
  input   signed [22:0] in2;  // sfix23_En20
  output  signed [38:0] mulOut;  // sfix39_En33


  wire signed [38:0] out;  // sfix39_En33


  multiplier_block u_multiplier (.clk(clk),
                                 .enb(enb),
                                 .in1(in1),  // sfix16_En13
                                 .in2(in2),  // sfix23_En20
                                 .out(out)  // sfix39_En33
                                 );

  assign mulOut = out;

endmodule  // Multiplier_block1