
// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\HDLFullySerialLMSModel\Reset_Control.v
// Created: 2024-02-10 22:35:17
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Reset_Control
// Source Path: HDLFullySerialLMSModel/HDL LMS Algorithm/Filter/Reset Control
// Hierarchy Level: 2
// Model version: 6.2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Reset_Control
          (clk,
           reset,
           enb,
           rst,
           count,
           filterEnb,
           enb_1,
           adapt,
           accRst,
           dataRst,
           coeffRst);


  input   clk;
  input   reset;
  input   enb;
  input   rst;
  input   [4:0] count;  // ufix5
  input   filterEnb;
  input   enb_1;
  input   adapt;
  output  accRst;
  output  dataRst;
  output  coeffRst;




  resetControl u_resetControl (.clk(clk),
                               .reset(reset),
                               .enb(enb),
                               .rst(rst),
                               .filtEnb(filterEnb),
                               .enb_1(enb_1),
                               .count(count),  // ufix5
                               .adaptin(adapt),
                               .accRst(accRst),
                               .dataRst(dataRst),
                               .coeffRst(coeffRst)
                               );

endmodule  // Reset_Control