
// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\HDLFullySerialLMSModel\Reset_Data.v
// Created: 2024-02-10 22:35:18
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Reset_Data
// Source Path: HDLFullySerialLMSModel/HDL LMS Algorithm/Filter/Reset Data
// Hierarchy Level: 2
// Model version: 6.2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Reset_Data
          (data,
           coeff,
           dataRst,
           coeffRst,
           delayLine,
           oldCoeff);


  input   signed [15:0] data;  // sfix16_En13
  input   signed [22:0] coeff;  // sfix23_En20
  input   dataRst;
  input   coeffRst;
  output  signed [15:0] delayLine;  // sfix16_En13
  output  signed [22:0] oldCoeff;  // sfix23_En20


  reg signed [15:0] delayLine_1;  // sfix16_En13
  reg signed [22:0] oldCoeff_1;  // sfix23_En20


  always @(coeff, coeffRst, data, dataRst) begin
    // Resets the input and coefficient memory.
    if (dataRst) begin
      // cast data type based on inputs
      delayLine_1 = 16'sb0000000000000000;
    end
    else begin
      delayLine_1 = data;
    end
    if (coeffRst) begin
      // cast data type based on inputs
      oldCoeff_1 = 23'sb00000000000000000000000;
    end
    else begin
      oldCoeff_1 = coeff;
    end
  end



  assign delayLine = delayLine_1;

  assign oldCoeff = oldCoeff_1;

endmodule  // Reset_Data

